### ISSUE TITLE
Compile error after updating to 1.6.5

### ISSUE THREAD

**Issue by AltTesterBot** [alttester/AltTester-Unity-SDK#575]
After updating from AltUnityTester Version 1.6.4 to 1.6.5 I am getting a compile error when wanting to build in the AltUnity Tester Editor.

The error is:
Assets\AltUnityTester\AltUnityServer\Commands\InputActions\AltUnityClickOnScreenCustom.cs(33,19): error CS0117: 'Input' does not contain a definition for 'SetCustomClick'

Build Target is StandaloneWindows64
I am using Unity version 2019.4.0f1

---
<sub>You can find the original issue from GitLab [here](https://gitlab.com/altom/altunity/altunitytester/-/issues/593).</sub>
